* Математическое моделирование

**Математическое моделирование** - это идеальное научное знаковое формальное моделирование,
при котором описание объекта осуществляется на языке математики, а исследование модели проводится 
с использованием тех или иных мат. методов.

Преимущества мат. моделирования очевидны и не имеет смысла их перечислять

Основные этапы метода мат. моделирования
1. Создание качественной модели
   
   Выясняется характер законов и связей, действуюх в системе.
   
   В зависимости от природы модели эти законы могут быть физическими, химическим, 
   биологическими, экономическими.

   Задача моделирования - выявить главные характерные черты явления

2. Постоновка математической задачи.

   1) Выделение существенных факторов. Если в системе действуют несколько факторов одного
      порядка, то они все должны быть либо учтены, либо отброшены
   2) Выделение дополнительных условий

   **Детерминированная задача** - модель описывается некоторыми уравнениями
   **Стохастическая** - модель описывается вероятностными законами

3. Изучение мат. модели.
   1) Мат. обоснование модели
      - Модель должна быть непротиворечива
      - Основание корректности дифференциональной модели
      - Доказаны теоремы существования, единственности, устойчивости
   2) Исследование качества модели
      - Проверка модели на крайних и предельных значениях
   3) Изучение мат. модели
      1) Численное изучение модели
	 - разработка алгоритма
	 - разработка численных методов исследования модели
	   (Модели должны быть общими)
	 - создание и реализация программы. Компьютерных эксперимент
   4) Полученные результаты изучаются и интерпретируются
      - Полученные данные сопостовляются с результатыми исследований других моделей
      - Модель и методы исследования уточняются и модифицируются
   5) Использование полученных результатов
      Предсказания новых явлений и закономерностей
