* Введение

Математическое моделирование - это идеальное научное знаковое формально емоделирование,
при котором описаие объекта осуществляется на языке математики, а исследование модели проводится
с использованием тех или иных математических методов.

** Что такое модель и моделирование

Методология - изучение методов познания.

Различают два уровня научного познания:
эмперический и теоретический

Моделилирование - метод познание окружающего мира, который можно отнести к общенаучным методам.

Модель - это материальный или мысленно представляемый объект, который в процессе познания
замещает объект-оригинал, сохраняя некоторые важные для данного исследования типичные 
его черты.

Любая модель **не** тождественна объекту-оригиналу.

Адекватность модели зависит от целей моделирования и принятых критериев.

Идеально адекватная модель принципиально невозможна в силу неполноты модели.

** Классификация моделей и моделирования

Использование моделирования на эмперическом и теоретическом уровне иследования приводит к 
делению на материальные и идеальные.

Материальное моделирование - это моделирование, при котором исследование объекта 
происходит с использованием его материального аналога воспроизводящего основные физические,
геометричесекие, динамические и функциональные характеристики данного объекта.

Идеальное моделирование отличается от материального тем, что оно основано не на материализованной аналогии
модели, а на аналогии идеальной, мыслимой и всегда носит теоретический характер.

Аналоговое моделирование - это моделирование, основанное на аналогии процессов и явлений, 
имеющих различную физическую природу, но одинаково описываемых формально
(одними и теми же математическими соотношениями, логическими и структурными схемами)

Исследование маетриальных моделей сводится к проведению ряда натурных эксперментов.

Идеальное моделирование разделяется на интуитивное и научное.

[[www.plantuml.com/plantuml/png/XP513e8m44Ntde8BS0UkOfITW57S6rYuyJ24s3WHsZEykP4jAvkcSVtVdxoVgQxz_jBVcjFkq3NdhgtRlc35ySAm87h7CJDX4Sml91ioiUWJYul3bKa7Z6zB3h4U6VMH1eBLGKT41uGv1TwXosSJ2r7UjoZBHFH_8IUVNWfuF2G3PKP5tG2cuwgwFVhtV040]]

Научное - логически обоснованное
- минимальное число предположений

Знаковое - в качестве моделей знаковые изображение(схемы, графики, символы)

Модели:
- когнетивная - мысленной образ 
- содержательная - представление модели на естественном языке

По функциональному признаку:
- описательная - любое описание объекта
- объяснительная - позволяет ответить на вопрос почему что-либо происходит
- прогностическая - описывает будующее объекта
- концептуальная - содержательная модель, при формулировке которой используются понятия 
  и представления предметных облостей знания, занимающихся изучением объекта моделирования.
- формальная модель представление концепутальной с помощью одного или нескольких формальных языков.

* Математическое моделирование

Математическое моделирование - это идеальное научное знаковое формальное моделирование,
при котором описание объекта осуществляется на языке математики, а исследование модели проводится 
с использованием тех или иных мат. методов.

Основные этапы метода математического моделирования
1. Создание качественной модели
   
   Выясняется характер законов и связей, действуюх в системе.
   
   В зависимости от природы модели эти законы могут быть физическими, химическим, 
   биологическими, экономическими.

2. Постоновка экономической задачи.
