* Введение

Математическое моделирование - это идеальное научное знаковое формальное моделирование,
при котором описание объекта осуществляется на языке математики, а исследование модели проводится
с использованием тех или иных математических методов.

** Что такое модель и моделирование

**Методология** - изучение методов познания.

**Метод** - совокупность приемов и операций практического и теоретического освоения действительности

Различают два уровня научного познания:
эмперический(наблюдение, эксперимент) и теоретический(формализация, идеализация)

**Моделирование** - метод познания окружающего мира, который можно отнести к общенаучным
методам(И эмпирический и теоретический).
**Моделирование** - процесс построения/использования модели

**Модель** - это материальный или мысленно представляемый объект, который в процессе познания
замещает объект-оригинал, сохраняя некоторые важные для данного исследования типичные 
его черты.

**Модель** - объект, сохраняющий важные для исследования черты оригинала. /Kirill's/

Любая модель **не** тождественна объекту-оригиналу.

**Адекватность** модели зависит от целей моделирования и принятых критериев.

Модель адекватна, если модель удовлетворяет исследователя и может служить основой
для прогнозирования поведения или свойств объекта

Идеально адекватная модель принципиально невозможна в силу неполноты модели.

Еще свойства моделей:

Простота

**Потенциальность** - мы хотим получить от модели больше знаний о реальном объекте, чем мы
использовали при построении модели


** Классификация моделей и моделирования

Использование моделирования на эмпирическом и теоретическом уровне исследования приводит к 
делению на материальные и идеальные.

Модели:
Материальные Идеальные

**Материальное моделирование** - это моделирование, при котором исследование объекта 
происходит с использованием его материального аналога воспроизводящего основные физические,
геометричесекие, динамические и функциональные характеристики данного объекта.

Идеальное моделирование отличается от материального тем, что оно основано не на материализованной аналогии
модели, а на аналогии идеальной, мыслимой и всегда носит теоретический характер.

Материальное моделирование может быть натурным или аналоговым

**Натурное моделирование** - реальному объекту ставится в соответствие уменьшенный или увеличенный
материальный аналог и изучение свойств модели с последующим переносом свойств модели на реальный объект

**Аналоговое моделирование** - это моделирование, основанное на аналогии процессов и явлений, 
имеющих различную физическую природу, но одинаково описываемых формально
(одними и теми же математическими соотношениями, логическими и структурными схемами)

Исследование материальных моделей сводится к проведению ряда натурных эксперментов, где вместо
объекта используется его физическая или аналоговая модель

Идеальное моделирование разделяется на интуитивное и научное.

[[http://www.plantuml.com/plantuml/png/XP513e8m44Ntde8BS0UkOfITW57S6rYuyJ24s3WHsZEykP4jAvkcSVtVdxoVgQxz_jBVcjFkq3NdhgtRlc35ySAm87h7CJDX4Sml91ioiUWJYul3bKa7Z6zB3h4U6VMH1eBLGKT41uGv1TwXosSJ2r7UjoZBHFH_8IUVNWfuF2G3PKP5tG2cuwgwFVhtV040][Схема разделения моделирования]]
Схема не полна - не хватает разделения материального моделирования

**Интуинтивное моделирование** - основано на интуинтивном представлении об объекте исследования,
не поддающихся формализации или не нуждающихся в них

**Научное** - логически обоснованное
- минимальное число гипотез об объекте исследования

Главное отличие - умение выполнять необходимые операции и действия по моделированию;
знание внутренних механизмов, которые при этом использются

**Знаковое** - в качестве моделей знаковые изображение(схемы, графики, символы)

Модели:
- когнитивная - мысленной образ объекта, его идеальная модель
- содержательная - представление когнитивной модели на естественном языке

По функциональному признаку содержательные модели делятся на:
- описательная - любое описание объекта
- объяснительная - позволяет ответить на вопрос почему что-либо происходит
- прогностическая - делает прогнозы поведения объекта (Не обязана включать объяснительную)
- концептуальная - содержательная модель, при формулировке которой используются понятия 
  и представлениях предметных областей знания, занимающихся изучением объекта моделирования.
- формальная - представление концепутальной с помощью одного или нескольких формальных языков.
